# Generated by Django 3.1.4 on 2020-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201222_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[("{'s': 'student'}", 'Student'), ("{'teacher': 't'}", 'Teacher'), ("{'rector': 'r'}", 'Rector'), ("{'head_of_dep': 'hod'}", 'Head Of Dep')], default='s', max_length=40),
        ),
    ]
