# Generated by Django 3.1.4 on 2020-12-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201222_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher'), ('r', 'Rector'), ('hod', 'Head Of Dep')], default='s', max_length=16),
        ),
    ]
