# Generated by Django 3.1.4 on 2020-12-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201223_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False, verbose_name='head of dep'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_rector',
            field=models.BooleanField(default=False, verbose_name='rector'),
        ),
    ]
