# Generated by Django 3.1.3 on 2020-12-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Chair name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name', max_length=100)),
                ('start_date', models.DateField(default='08-12-2020')),
                ('graduate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Spec name', max_length=10)),
                ('unique_cod', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Univer name', max_length=100)),
            ],
        ),
    ]
