# Generated by Django 3.1.3 on 2020-12-08 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='head_of_dep',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_dep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chair',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chair',
            name='univer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univers.univer'),
        ),
        migrations.AddField(
            model_name='groupspec',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='univers.specialization'),
        ),
        migrations.AddField(
            model_name='univer',
            name='rector',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
