# Generated by Django 3.1.3 on 2020-12-08 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0003_auto_20201208_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.UUIDField(default=uuid.UUID('62245756-b261-4e24-b5b8-36b238bcb870'))),
            ],
        ),
        migrations.RemoveField(
            model_name='groupspec',
            name='test',
        ),
    ]
