# Generated by Django 3.1.3 on 2020-12-08 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0004_auto_20201208_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='test',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
