# Generated by Django 3.1.3 on 2020-12-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0006_auto_20201208_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspec',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_specs', to='univers.specialization'),
        ),
    ]
