# Generated by Django 3.1.3 on 2020-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0007_auto_20201209_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspec',
            name='name',
            field=models.CharField(blank=True, help_text='Group name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupspec',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
