# Generated by Django 3.1.3 on 2020-12-09 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0008_auto_20201209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspec',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
