# Generated by Django 3.1.3 on 2020-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0009_auto_20201209_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspec',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
