# Generated by Django 3.1.3 on 2020-12-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0010_auto_20201209_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univers.chair'),
        ),
    ]
