# Generated by Django 3.1.3 on 2020-12-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0011_specialization_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
