# Generated by Django 3.1.3 on 2020-12-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univers', '0012_auto_20201210_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='head_of_dep',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairs_hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chair',
            name='teacher',
        ),
        migrations.AddField(
            model_name='chair',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
