# Generated by Django 3.1.3 on 2020-12-10 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univers', '0013_auto_20201210_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='teacher',
        ),
        migrations.AddField(
            model_name='chair',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
