# Generated by Django 3.1.3 on 2020-12-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0015_auto_20201210_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='univer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='univer_chair', to='univers.univer'),
        ),
    ]
