# Generated by Django 3.1.3 on 2020-12-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0016_auto_20201210_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='univer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='univer_chairs', to='univers.univer'),
        ),
    ]
