# Generated by Django 3.1.3 on 2020-12-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0017_auto_20201210_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='univers.chair'),
        ),
    ]
