# Generated by Django 3.1.3 on 2020-12-11 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('univers', '0018_auto_20201211_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupspec',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
